apiVersion: v1
kind: Secret
metadata:
  name: studyboard-secret
  namespace: studyboard
  labels:
    app.kubernetes.io/name: studyboard
type: Opaque
stringData:
  AUTH_DB_USER: studyboard_auth_app
  AUTH_DB_PASS: "AuthSenha@2026"
  TASK_DB_USER: studyboard_task_app
  TASK_DB_PASS: "TaskSenha@2026"
  MARIADB_ROOT_PASSWORD: "RootSenha@2026"
