apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-db
  namespace: studyboard
  labels:
    app: tasks-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-db
  template:
    metadata:
      labels:
        app: tasks-db
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mariadb
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: studyboard_tasks
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: studyboard-secret
                  key: TASK_DB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: studyboard-secret
                  key: TASK_DB_PASS
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: studyboard-secret
                  key: MARIADB_ROOT_PASSWORD
          volumeMounts:
            - name: tasks-db-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: tasks-db-tmp
              mountPath: /tmp
            - name: tasks-db-var-tmp
              mountPath: /var/tmp
            - name: tasks-db-run
              mountPath: /run/mysqld
            - name: tasks-db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: tasks-db-init
          configMap:
            name: tasks-db-init
        - name: tasks-db-tmp
          emptyDir:
            medium: Memory
        - name: tasks-db-var-tmp
          emptyDir:
            medium: Memory
        - name: tasks-db-run
          emptyDir:
            medium: Memory
        - name: tasks-db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-db
  namespace: studyboard
  labels:
    app: tasks-db
spec:
  type: ClusterIP
  selector:
    app: tasks-db
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
