name: "Formativa"

on:
  - push
  - workflow_dispatch

jobs: 
  testes-unitarios:
    name: Executar testes unitários
    runs-on: self-hosted
    #customizar a image do runner para incluir o PHP e o Composer

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar PHP
        run: php -v

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist

      - name: Rodar PHPUnit
        run: ./vendor/bin/phpunit